version: "3.8"
services:
  microblog-local-db:
    container_name: microblog-local-db
    image: postgres
    restart: always
    volumes:
      - microblog-pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  microblog-pgdata:
    external: true
